/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountSaveRequest { 
    iban?: string;
    customerId?: string;
    currency?: string;
    productName?: string;
    openYear?: number;
    type?: string;
    balance?: number;
    lastTransactionDate?: string;
}

