/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountListItem } from './accountListItem';


export interface AccountListResponse { 
    accounts?: Array<AccountListItem>;
    totalCount?: number;
    pageNumber?: number;
    pageSize?: number;
}

