/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountListItem { 
    iban?: string;
    customerId?: string;
    customerName?: string;
    currency?: string;
    productName?: string;
    openYear?: number;
    type?: string;
    balance?: string;
    cityName?: string;
    branchName?: string;
    photoUrl?: string;
}

