/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BranchWorkloadItem { 
    branchId?: string;
    branchName?: string;
    totalCustomer?: number;
    activeCustomer?: number;
    transferLoad?: number;
    havale?: number;
    eft?: number;
    fast?: number;
    swift?: number;
    autoPayment?: number;
    loadPercent?: number;
}

