/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BranchWorkloadItem } from './branchWorkloadItem';


export interface BranchWorkloadResponse { 
    cityId?: string;
    cityName?: string;
    branches?: Array<BranchWorkloadItem>;
    totalTransferLoad?: number;
}

