/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BranchListItem } from './branchListItem';


export interface BranchListResponse { 
    branches?: Array<BranchListItem>;
    totalCount?: number;
}

