/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomerDetailResponse { 
    found?: boolean;
    id?: string;
    customerNumber?: string;
    fullName?: string;
    age?: number;
    segment?: string;
    creditScore?: number;
    photoUrl?: string;
    phone?: string;
    joinDate?: string;
    cityId?: string;
    cityName?: string;
    branchId?: string;
    branchName?: string;
    status?: string;
    statusName?: string;
    transferType?: string;
    transferTypeName?: string;
    dailyTransferCount?: number;
    dailyTransferLimit?: number;
    overDailyLimit?: boolean;
    accountIban?: string;
}

