/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomerListItem { 
    id?: string;
    customerNumber?: string;
    fullName?: string;
    segment?: string;
    cityName?: string;
    branchName?: string;
    status?: string;
    statusName?: string;
    transferTypeName?: string;
    creditScore?: number;
    photoUrl?: string;
    overDailyLimit?: boolean;
}

