/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomerSaveRequest { 
    id?: string;
    customerNumber?: string;
    fullName?: string;
    age?: number;
    segment?: string;
    creditScore?: number;
    phone?: string;
    joinDate?: string;
    cityId?: string;
    branchId?: string;
    status?: string;
    transferType?: string;
    dailyTransferLimit?: number;
}

