/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerListItem } from './customerListItem';


export interface CustomerListResponse { 
    customerList?: Array<CustomerListItem>;
    totalCount?: number;
    pageNumber?: number;
    pageSize?: number;
}

