/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */


export interface NotificationReadResponse { 
    success?: boolean;
    unreadCount?: number;
    message?: string;
}
