/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */
import { NotificationItem } from './notificationItem';


export interface NotificationListResponse { 
    items?: Array<NotificationItem>;
    unreadCount?: number;
    totalCount?: number;
}
