/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportEntryRequest { 
    reportName?: string;
    reportType?: string;
    cityId?: string;
    branchId?: string;
    startDate?: string;
    endDate?: string;
}

