/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportEntryExecuteResponse { 
    success?: boolean;
    reportNo?: string;
    reportName?: string;
    reportTypeName?: string;
    cityName?: string;
    period?: string;
    customerCount?: number;
    transferCount?: number;
    createdDate?: string;
    message?: string;
}

