/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportListItem { 
    reportNo?: string;
    reportName?: string;
    reportType?: string;
    reportTypeName?: string;
    cityName?: string;
    branchName?: string;
    period?: string;
    customerCount?: number;
    transferCount?: number;
    createdDate?: string;
}

