/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusCount } from './statusCount';


export interface SummaryResponse { 
    totalCustomer?: number;
    active?: number;
    passive?: number;
    blocked?: number;
    followUp?: number;
    overDailyLimit?: number;
    branchCount?: number;
    statusDistribution?: Array<StatusCount>;
}

