/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrendPoint } from './trendPoint';


export interface TransferTrendResponse { 
    cityName?: string;
    points?: Array<TrendPoint>;
    totalTransferCount?: number;
    averageTransferCount?: number;
}

