/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransferListItem { 
    id?: string;
    customerId?: string;
    customerName?: string;
    customerNumber?: string;
    cityName?: string;
    branchName?: string;
    type?: string;
    typeName?: string;
    receiverName?: string;
    transferTime?: string;
    amount?: string;
    status?: string;
    statusName?: string;
}

