/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransferTypeItem } from './transferTypeItem';


export interface TransferTypeListResponse { 
    types?: Array<TransferTypeItem>;
    totalTransferCount?: number;
}

