/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransferListItem } from './transferListItem';


export interface TransferListResponse { 
    transfers?: Array<TransferListItem>;
    totalCount?: number;
    pageNumber?: number;
    pageSize?: number;
}

