/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransferCreateConfirmResponse { 
    valid?: boolean;
    customerId?: string;
    customerName?: string;
    customerNumber?: string;
    branchName?: string;
    cityName?: string;
    typeName?: string;
    receiverName?: string;
    receiverIban?: string;
    amount?: string;
    currency?: string;
    fee?: string;
    total?: string;
    currentTransferCount?: number;
    dailyTransferLimit?: number;
    willExceedLimit?: boolean;
    message?: string;
}
