/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransferCreateExecuteResponse { 
    success?: boolean;
    transferId?: string;
    customerName?: string;
    typeName?: string;
    receiverName?: string;
    receiverIban?: string;
    amount?: string;
    currency?: string;
    newTransferCount?: number;
    message?: string;
}
