/**
 * Bankatek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransferListRequest { 
    cityId?: string;
    branchId?: string;
    customerId?: string;
    type?: string;
    status?: string;
    onlyOverLimit?: boolean;
    pageNumber?: number;
    pageSize?: number;
}

