export * from './analyticsController.service';
import { AnalyticsControllerService } from './analyticsController.service';
export * from './dashboardController.service';
import { DashboardControllerService } from './dashboardController.service';
export * from './loginController.service';
import { LoginControllerService } from './loginController.service';
export * from './menuController.service';
import { MenuControllerService } from './menuController.service';
export * from './customerController.service';
import { CustomerControllerService } from './customerController.service';
export * from './regionController.service';
import { RegionControllerService } from './regionController.service';
export * from './reportEntryController.service';
import { ReportEntryControllerService } from './reportEntryController.service';
export * from './resourceController.service';
import { ResourceControllerService } from './resourceController.service';
export * from './settingController.service';
import { SettingControllerService } from './settingController.service';
export * from './transferController.service';
import { TransferControllerService } from './transferController.service';
export * from './branchController.service';
import { BranchControllerService } from './branchController.service';
export * from './accountController.service';
import { AccountControllerService } from './accountController.service';
export const APIS = [AnalyticsControllerService, DashboardControllerService, LoginControllerService, MenuControllerService, CustomerControllerService, RegionControllerService, ReportEntryControllerService, ResourceControllerService, SettingControllerService, TransferControllerService, BranchControllerService, AccountControllerService];
